shellchecks for apply-system

diff --git a/bin/apply-system b/bin/apply-system
--- a/bin/apply-system
+++ b/bin/apply-system
@@ -1,18 +1,20 @@
-#!/bin/sh
-set -x
-DARWIN_REBUILD=`which darwin-rebuild`
-NIXOS_REBUILD=`which nixos-rebuild`
-if [ ! -z "${DARWIN_REBUILD}" ]; then
-	echo "Found darwin-rebuild at ${DARWIN_REBUILD}"
-	pushd ~/.dotfiles
-	darwin-rebuild -v switch --flake .#
-	popd
-elif [ ! -z "${NIXOS_REBUILD}" ]; then
-	echo "Found nixos-rebuild at ${NIXOS_REBUILD}"
-	pushd ~/.dotfiles
+#!env bash
+# shellcheck disable=SC2239
+set -xeuo pipefail
+
+if which darwin-rebuild
+then
+  echo "Found darwin-rebuild at $(which darwin-rebuild)"
+  pushd ~/.dotfiles || exit
+  darwin-rebuild -v switch --flake .#
+  popd || exit
+elif which nixos-rebuild
+then
+  echo "Found nixos-rebuild at $(which nixos-rebuild)"
+	pushd ~/.dotfiles || exit
 	sudo nixos-rebuild -v switch --flake .#
-	popd
+	popd || exit
 else
-	echo "Could not find nixos-rebuild or darwin-rebuild ... Bailing out!"
+	echo "Error: Could not find nixos-rebuild or darwin-rebuild ... Bailing out!"
 	exit 1
 fi
