retab shell scripts

diff --git a/bin/apply-nixium-legacy b/bin/apply-nixium-legacy
--- a/bin/apply-nixium-legacy
+++ b/bin/apply-nixium-legacy
@@ -4,16 +4,16 @@ set -xeuo pipefail
 if which darwin-rebuild
 then
   echo "Found darwin-rebuild at $(which darwin-rebuild)"
-	echo "Error: darwin-rebuild doesn't support --target-host builds ... Bailing out!"
-	exit 1
+  echo "Error: darwin-rebuild doesn't support --target-host builds ... Bailing out!"
+  exit 1
 elif which nixos-rebuild
 then
   echo "Found nixos-rebuild at $(which nixos-rebuild)"
-	pushd ~/.dotfiles || exit 1
+  pushd ~/.dotfiles || exit 1
     nixos-rebuild -v switch --target-host root@nixium.boxchop.city --flake .#nixium
-	popd || exit 1
-else
-	echo "Error: Could not find nixos-rebuild or darwin-rebuild ... Bailing out!"
   popd || exit 1
-	exit 1
+else
+  echo "Error: Could not find nixos-rebuild or darwin-rebuild ... Bailing out!"
+  popd || exit 1
+  exit 1
 fi
diff --git a/bin/apply-system b/bin/apply-system
--- a/bin/apply-system
+++ b/bin/apply-system
@@ -10,10 +10,10 @@ then
 elif which nixos-rebuild
 then
   echo "Found nixos-rebuild at $(which nixos-rebuild)"
-	pushd ~/.dotfiles || exit 1
-	sudo nixos-rebuild -v switch --flake .#
-	popd || exit 1
+  pushd ~/.dotfiles || exit 1
+  sudo nixos-rebuild -v switch --flake .#
+  popd || exit 1
 else
-	echo "Error: Could not find nixos-rebuild or darwin-rebuild ... Bailing out!"
-	exit 1
+  echo "Error: Could not find nixos-rebuild or darwin-rebuild ... Bailing out!"
+  exit 1
 fi
diff --git a/bin/apply-user b/bin/apply-user
--- a/bin/apply-user
+++ b/bin/apply-user
@@ -10,8 +10,8 @@ fi
 
 if [ ! "$(whoami)" ]
 then
-	echo "Error: Not able to determine USER ... Bailing out!";
-	exit 1;
+  echo "Error: Not able to determine USER ... Bailing out!";
+  exit 1;
 else
   USER=$(whoami)
 fi
diff --git a/bin/build-system b/bin/build-system
--- a/bin/build-system
+++ b/bin/build-system
@@ -4,22 +4,22 @@ set -xeuo pipefail
 if which darwin-rebuild
 then
   echo "Found darwin-rebuild at $(which darwin-rebuild)"
-	pushd ~/.dotfiles || exit 1
-	if darwin-rebuild -v build --flake .#
+  pushd ~/.dotfiles || exit 1
+  if darwin-rebuild -v build --flake .#
   then
     nvd diff /run/current-system ./result
   fi
-	popd || exit 1
+  popd || exit 1
 elif which nixos-rebuild
 then
   echo "Found nixos-rebuild at $(which nixos-rebuild)"
-	pushd ~/.dotfiles || exit 1
-	if nixos-rebuild -v build --flake .#
+  pushd ~/.dotfiles || exit 1
+  if nixos-rebuild -v build --flake .#
   then
     nvd diff /run/current-system ./result
   fi
-	popd || exit 1
+  popd || exit 1
 else
-	echo "Error: Could not find nixos-rebuild or darwin-rebuild ... Bailing out!"
-	exit 1
+  echo "Error: Could not find nixos-rebuild or darwin-rebuild ... Bailing out!"
+  exit 1
 fi
